# Generated by Django 3.2.9 on 2021-11-18 17:18

from django.db import migrations, models
from ..validators import validate_file_size


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='store/images', validators=[validate_file_size]),
        ),
    ]
